language: c

sudo: false

cache:
  directories:
    - ~/.ghc
    - ~/.cabal
    - ~/.stack

addons:
  apt:
    packages:
    - libgmp-dev

matrix:
  include:
    - env: TYPE=cabal CABALVER=1.24 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=1.24 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: TYPE=stack ARGS="--resolver lts-2"
    - env: TYPE=stack ARGS="--resolver lts-6"
    - env: TYPE=stack ARGS="--stack-yaml stack.yaml"

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - mkdir -pv ~/.local/bin
  - case "$TYPE" in
      cabal) travis_retry cabal update && cabal install --only-dependencies --enable-tests ;;
      stack) travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack' ;;
    esac

script:
  - case "$TYPE" in
      cabal) cabal configure --enable-tests -v2 && cabal build && cabal test --show-details=always && cabal sdist && cabal haddock | grep "100%" | wc -l | grep "2" ;;
      stack)
        echo "$(stack --version) @ $(which stack)"
        stack --no-terminal --install-ghc $ARGS test
        ;;
    esac

notifications:
  email:
    on_success: never
    on_failure: always
