language: c

sudo: false

cache:
  directories:
    - ~/.cabal/packages
    - ~/.cabal/store
    - ~/.stack

addons:
  apt:
    packages:
    - libgmp-dev

matrix:
  include:
    - env: TYPE=cabal CABALVER=2.4 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-2.4,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=2.4 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-2.4,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=2.4 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=2.4 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=2.4 GHCVER=8.4.3
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.4.3], sources: [hvr-ghc]}}
    - env: TYPE=cabal CABALVER=2.4 GHCVER=8.6.1
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.1], sources: [hvr-ghc]}}
    - env: TYPE=stack ARGS="--stack-yaml lts-2.yaml"
    - env: TYPE=stack ARGS="--stack-yaml lts-6.yaml"
    - env: TYPE=stack ARGS="--stack-yaml stack.yaml"

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - mkdir -pv ~/.local/bin
  - case "$TYPE" in
      cabal) travis_retry cabal update ;;
      stack) travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack' ;;
    esac

script:
  - |
    set -ex # Error out after first failure and print each command before executing
    case "$TYPE" in
      cabal)
        cabal new-build --enable-tests --enable-benchmarks --flags=dev
        cabal new-test
        cabal new-haddock
        cabal sdist
        ;;
      stack)
        stack --version
        stack --no-terminal --install-ghc $ARGS test
        ;;
    esac
    set +ex # Stop printing each command

notifications:
  email:
    on_success: never
    on_failure: always
